export const ERROR_CODE = {
  // Common
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  USER_DISABLED: 'USER_DISABLED',
  USER_DELETED: 'USER_DELETED',

  // Affiliate
  AFFILIATE_LINK_INVALID: 'AFFILIATE_LINK_INVALID',
  AFFILIATE_LINK_NOT_FOUND: 'AFFILIATE_LINK_NOT_FOUND',
  AFFILIATE_CONVERT_FAILED: 'AFFILIATE_CONVERT_FAILED',
  AFFILIATE_PROVIDER_ERROR: 'AFFILIATE_PROVIDER_ERROR',
  AFFILIATE_PROVIDER_TIMEOUT: 'AFFILIATE_PROVIDER_TIMEOUT',

  // Shopee
  SHOPEE_LINK_INVALID: 'SHOPEE_LINK_INVALID',
  SHOPEE_COOKIE_INVALID: 'SHOPEE_COOKIE_INVALID',
  SHOPEE_COOKIE_EXPIRED: 'SHOPEE_COOKIE_EXPIRED',
  SHOPEE_CONVERT_LINK_FAILED: 'SHOPEE_CONVERT_LINK_FAILED',

  // Transaction / Commission
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  COMMISSION_NOT_FOUND: 'COMMISSION_NOT_FOUND',
  COMMISSION_NOT_CONFIRMED: 'COMMISSION_NOT_CONFIRMED',
  COMMISSION_ALREADY_PROCESSED: 'COMMISSION_ALREADY_PROCESSED',

  // Cashback
  CASHBACK_NOT_FOUND: 'CASHBACK_NOT_FOUND',
  CASHBACK_ALREADY_PAID: 'CASHBACK_ALREADY_PAID',
  CASHBACK_NOT_ELIGIBLE: 'CASHBACK_NOT_ELIGIBLE',

  // Bank
  BANK_ACCOUNT_NOT_FOUND: 'BANK_ACCOUNT_NOT_FOUND',
  BANK_ACCOUNT_INVALID: 'BANK_ACCOUNT_INVALID',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ADMIN_ONLY: 'ADMIN_ONLY',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
